// SPDX-FileCopyrightText: © 2025 StreamKit Contributors
//
// SPDX-License-Identifier: MPL-2.0

//! FFI panic boundary helpers.
//!
//! Every `extern "C"` trampoline generated by the plugin entry macros must
//! run under one of these guards so that a panic inside plugin code never
//! unwinds across the C ABI boundary (which is instant UB on all platforms).
//!
//! # `AssertUnwindSafe` justification
//!
//! The closures capture raw pointers and references derived from them.
//! After a panic the plugin instance may be in an inconsistent state, but
//! the host will receive an error return and can decide to destroy the
//! instance.  The alternative — aborting the entire server — is strictly
//! worse.

use std::ffi::CString;
use std::panic::{catch_unwind, AssertUnwindSafe};

use crate::types;

/// Extract a human-readable message from a panic payload.
///
/// Handles `&str`, `String`, and `Box<dyn Error + Send + Sync>` payloads
/// (the latter covers e.g. [`std::panic::panic_any`] with a boxed error).
pub fn panic_message(payload: &(dyn std::any::Any + Send)) -> String {
    if let Some(s) = payload.downcast_ref::<&str>() {
        return (*s).to_string();
    }
    if let Some(s) = payload.downcast_ref::<String>() {
        return s.clone();
    }
    if let Some(e) = payload.downcast_ref::<Box<dyn std::error::Error + Send + Sync>>() {
        return e.to_string();
    }
    "unknown panic".to_string()
}

/// Guard a trampoline that returns [`types::CResult`].
pub fn guard_result<F: FnOnce() -> types::CResult>(f: F) -> types::CResult {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(result) => result,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let err = crate::conversions::error_to_c(format!("plugin panicked: {msg}"));
            types::CResult::error(err)
        },
    }
}

/// Guard a trampoline that returns [`types::CPluginHandle`] (null on panic).
pub fn guard_handle<F: FnOnce() -> types::CPluginHandle>(f: F) -> types::CPluginHandle {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(handle) => handle,
        Err(payload) => {
            let msg = panic_message(&*payload);
            // Store in thread-local for host retrieval via error_to_c.
            let _ = crate::conversions::error_to_c(format!(
                "plugin panicked in create_instance: {msg}"
            ));
            std::ptr::null_mut()
        },
    }
}

/// Guard a trampoline that returns `*const T` (null on panic).
pub fn guard_ptr<T, F: FnOnce() -> *const T>(f: F) -> *const T {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(ptr) => ptr,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let _ =
                crate::conversions::error_to_c(format!("plugin panicked in get_metadata: {msg}"));
            std::ptr::null()
        },
    }
}

/// Guard a trampoline that returns [`types::CTickResult`].
pub fn guard_tick<F: FnOnce() -> types::CTickResult>(f: F) -> types::CTickResult {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(result) => result,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let err = crate::conversions::error_to_c(format!("plugin panicked: {msg}"));
            types::CTickResult::error(err)
        },
    }
}

/// Guard a trampoline that returns [`types::CSchemaResult`].
pub fn guard_schema<F: FnOnce() -> types::CSchemaResult>(f: F) -> types::CSchemaResult {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(result) => result,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let err = crate::conversions::error_to_c(format!("plugin panicked: {msg}"));
            types::CSchemaResult::error(err)
        },
    }
}

/// Guard a trampoline that returns [`types::CSourceConfig`].
///
/// On panic the returned config has `is_source: false`, which silently
/// reclassifies the node as a processor.  A `tracing::error!` is emitted
/// so this does not go unnoticed.
pub fn guard_source_config<F: FnOnce() -> types::CSourceConfig>(f: F) -> types::CSourceConfig {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(cfg) => cfg,
        Err(payload) => {
            let msg = panic_message(&*payload);
            tracing::error!(
                "plugin panicked in get_source_config \
                 (node reclassified as non-source): {msg}"
            );
            let _ = crate::conversions::error_to_c(format!(
                "plugin panicked in get_source_config: {msg}"
            ));
            types::CSourceConfig { is_source: false, tick_interval_us: 0, max_ticks: 0 }
        },
    }
}

/// Guard a trampoline that returns nothing (e.g. `destroy_instance`).
///
/// # Double-panic risk
///
/// In `__plugin_destroy_instance`, `cleanup()` runs first and then the
/// plugin value is dropped.  If `cleanup()` panics **and** `Drop` also
/// panics, the process aborts (Rust double-panic rule).  To mitigate
/// this, `__plugin_destroy_instance` wraps `cleanup()` in its own
/// nested `catch_unwind`, so a `cleanup` panic does not propagate into
/// the `Drop`.  Plugin authors should still avoid panicking in `Drop`.
pub fn guard_unit<F: FnOnce()>(f: F) {
    if let Err(payload) = catch_unwind(AssertUnwindSafe(f)) {
        let msg = panic_message(&*payload);
        let _ = crate::conversions::error_to_c(format!("plugin panicked in cleanup: {msg}"));
    }
}

/// Create a [`CString`], sanitizing embedded null bytes instead of panicking.
///
/// If `s` contains null bytes they are stripped and a `tracing::error!` is
/// emitted with `context` so plugin authors can locate the mistake.  This
/// avoids a panic inside `__plugin_get_metadata` that [`guard_ptr`] would
/// silently turn into a null return.
///
/// # Panics
///
/// Cannot panic in practice — after stripping all null bytes,
/// `CString::new` is infallible.
pub fn cstring_lossy(s: &str, context: &str) -> CString {
    match CString::new(s) {
        Ok(c) => c,
        Err(e) => {
            tracing::error!("metadata field '{context}' contains null bytes: {e}");
            let sanitized = s.replace('\0', "");
            // After removing all null bytes CString::new cannot fail.
            #[allow(clippy::unwrap_used)]
            CString::new(sanitized).unwrap()
        },
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn guard_result_catches_panic() {
        let result = guard_result(|| panic!("boom"));
        assert!(!result.success);
        assert!(!result.error_message.is_null());
        let msg = unsafe { crate::conversions::c_str_to_string(result.error_message) }
            .expect("valid UTF-8");
        assert!(msg.contains("boom"), "expected panic message, got: {msg}");
    }

    #[test]
    fn guard_result_passes_through_ok() {
        let result = guard_result(types::CResult::success);
        assert!(result.success);
    }

    #[test]
    fn guard_handle_returns_null_on_panic() {
        let handle = guard_handle(|| panic!("handle boom"));
        assert!(handle.is_null());
    }

    #[test]
    fn guard_ptr_returns_null_on_panic() {
        let ptr: *const u8 = guard_ptr(|| panic!("ptr boom"));
        assert!(ptr.is_null());
    }

    #[test]
    fn guard_tick_catches_panic() {
        let result = guard_tick(|| panic!("tick boom"));
        assert!(!result.result.success);
    }

    #[test]
    fn guard_schema_catches_panic() {
        let result = guard_schema(|| panic!("schema boom"));
        assert!(!result.success);
    }

    #[test]
    fn guard_source_config_returns_default_on_panic() {
        let cfg = guard_source_config(|| panic!("config boom"));
        assert!(!cfg.is_source);
        assert_eq!(cfg.tick_interval_us, 0);
        assert_eq!(cfg.max_ticks, 0);
    }

    #[test]
    fn guard_unit_catches_panic() {
        guard_unit(|| panic!("unit boom"));
    }

    #[test]
    fn panic_message_extracts_str() {
        let msg = std::panic::catch_unwind(|| panic!("hello")).unwrap_err();
        assert_eq!(panic_message(&*msg), "hello");
    }

    #[test]
    fn panic_message_extracts_string() {
        let msg = std::panic::catch_unwind(|| panic!("{}", "formatted")).unwrap_err();
        assert_eq!(panic_message(&*msg), "formatted");
    }

    #[test]
    fn panic_message_unknown_type() {
        let msg = std::panic::catch_unwind(|| {
            std::panic::panic_any(42_i32);
        })
        .unwrap_err();
        assert_eq!(panic_message(&*msg), "unknown panic");
    }

    #[test]
    fn panic_message_extracts_boxed_error() {
        let err: Box<dyn std::error::Error + Send + Sync> = "boxed error".into();
        let msg = std::panic::catch_unwind(AssertUnwindSafe(|| {
            std::panic::panic_any(err);
        }))
        .unwrap_err();
        assert_eq!(panic_message(&*msg), "boxed error");
    }

    #[test]
    fn cstring_lossy_clean_string() {
        let c = cstring_lossy("hello", "test");
        assert_eq!(c.to_str().unwrap(), "hello");
    }

    #[test]
    fn cstring_lossy_strips_null_bytes() {
        let c = cstring_lossy("hel\0lo", "test field");
        assert_eq!(c.to_str().unwrap(), "hello");
    }
}
