// SPDX-FileCopyrightText: © 2025 StreamKit Contributors
//
// SPDX-License-Identifier: MPL-2.0

//! FFI panic boundary helpers.
//!
//! Every `extern "C"` trampoline generated by the plugin entry macros must
//! run under one of these guards so that a panic inside plugin code never
//! unwinds across the C ABI boundary (which is instant UB on all platforms).
//!
//! # `AssertUnwindSafe` justification
//!
//! The closures capture raw pointers and references derived from them.
//! After a panic the plugin instance may be in an inconsistent state, but
//! the host will receive an error return and can decide to destroy the
//! instance.  The alternative — aborting the entire server — is strictly
//! worse.

use std::panic::{catch_unwind, AssertUnwindSafe};

use crate::types;

/// Extract a human-readable message from a panic payload.
fn panic_message(payload: &(dyn std::any::Any + Send)) -> String {
    payload.downcast_ref::<&str>().map_or_else(
        || {
            payload
                .downcast_ref::<String>()
                .map_or_else(|| "unknown panic".to_string(), Clone::clone)
        },
        |s| (*s).to_string(),
    )
}

/// Guard a trampoline that returns [`types::CResult`].
pub fn guard_result<F: FnOnce() -> types::CResult>(f: F) -> types::CResult {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(result) => result,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let err = crate::conversions::error_to_c(format!("plugin panicked: {msg}"));
            types::CResult::error(err)
        },
    }
}

/// Guard a trampoline that returns [`types::CPluginHandle`] (null on panic).
pub fn guard_handle<F: FnOnce() -> types::CPluginHandle>(f: F) -> types::CPluginHandle {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(handle) => handle,
        Err(payload) => {
            let msg = panic_message(&*payload);
            // Best-effort log; error_to_c is thread-local so this is safe.
            let _ = crate::conversions::error_to_c(format!(
                "plugin panicked in create_instance: {msg}"
            ));
            std::ptr::null_mut()
        },
    }
}

/// Guard a trampoline that returns `*const T` (null on panic).
pub fn guard_ptr<T, F: FnOnce() -> *const T>(f: F) -> *const T {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(ptr) => ptr,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let _ =
                crate::conversions::error_to_c(format!("plugin panicked in get_metadata: {msg}"));
            std::ptr::null()
        },
    }
}

/// Guard a trampoline that returns [`types::CTickResult`].
pub fn guard_tick<F: FnOnce() -> types::CTickResult>(f: F) -> types::CTickResult {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(result) => result,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let err = crate::conversions::error_to_c(format!("plugin panicked: {msg}"));
            types::CTickResult::error(err)
        },
    }
}

/// Guard a trampoline that returns [`types::CSchemaResult`].
pub fn guard_schema<F: FnOnce() -> types::CSchemaResult>(f: F) -> types::CSchemaResult {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(result) => result,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let err = crate::conversions::error_to_c(format!("plugin panicked: {msg}"));
            types::CSchemaResult::error(err)
        },
    }
}

/// Guard a trampoline that returns [`types::CSourceConfig`].
pub fn guard_source_config<F: FnOnce() -> types::CSourceConfig>(f: F) -> types::CSourceConfig {
    match catch_unwind(AssertUnwindSafe(f)) {
        Ok(cfg) => cfg,
        Err(payload) => {
            let msg = panic_message(&*payload);
            let _ = crate::conversions::error_to_c(format!(
                "plugin panicked in get_source_config: {msg}"
            ));
            types::CSourceConfig { is_source: false, tick_interval_us: 0, max_ticks: 0 }
        },
    }
}

/// Guard a trampoline that returns nothing (swallow panic, log it).
pub fn guard_unit<F: FnOnce()>(f: F) {
    if let Err(payload) = catch_unwind(AssertUnwindSafe(f)) {
        let msg = panic_message(&*payload);
        let _ = crate::conversions::error_to_c(format!("plugin panicked in cleanup: {msg}"));
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn guard_result_catches_panic() {
        let result = guard_result(|| panic!("boom"));
        assert!(!result.success);
        assert!(!result.error_message.is_null());
        let msg = unsafe { crate::conversions::c_str_to_string(result.error_message) }
            .expect("valid UTF-8");
        assert!(msg.contains("boom"), "expected panic message, got: {msg}");
    }

    #[test]
    fn guard_result_passes_through_ok() {
        let result = guard_result(types::CResult::success);
        assert!(result.success);
    }

    #[test]
    fn guard_handle_returns_null_on_panic() {
        let handle = guard_handle(|| panic!("handle boom"));
        assert!(handle.is_null());
    }

    #[test]
    fn guard_ptr_returns_null_on_panic() {
        let ptr: *const u8 = guard_ptr(|| panic!("ptr boom"));
        assert!(ptr.is_null());
    }

    #[test]
    fn guard_tick_catches_panic() {
        let result = guard_tick(|| panic!("tick boom"));
        assert!(!result.result.success);
    }

    #[test]
    fn guard_schema_catches_panic() {
        let result = guard_schema(|| panic!("schema boom"));
        assert!(!result.success);
    }

    #[test]
    fn guard_source_config_returns_default_on_panic() {
        let cfg = guard_source_config(|| panic!("config boom"));
        assert!(!cfg.is_source);
        assert_eq!(cfg.tick_interval_us, 0);
        assert_eq!(cfg.max_ticks, 0);
    }

    #[test]
    fn guard_unit_catches_panic() {
        guard_unit(|| panic!("unit boom"));
    }

    #[test]
    fn panic_message_extracts_str() {
        let msg = std::panic::catch_unwind(|| panic!("hello")).unwrap_err();
        assert_eq!(panic_message(&*msg), "hello");
    }

    #[test]
    fn panic_message_extracts_string() {
        let msg = std::panic::catch_unwind(|| panic!("{}", "formatted")).unwrap_err();
        assert_eq!(panic_message(&*msg), "formatted");
    }

    #[test]
    fn panic_message_unknown_type() {
        let msg = std::panic::catch_unwind(|| {
            std::panic::panic_any(42_i32);
        })
        .unwrap_err();
        assert_eq!(panic_message(&*msg), "unknown panic");
    }
}
