// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// AudioFrameShape is used for storage in variant or result types.
type AudioFrameShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(AudioFrame{})]byte
}
