// Code generated by wit-bindgen-go. DO NOT EDIT.

package node

import (
	"github.com/streamkit/streamkit-codex/plugin-sdk/go/bindings/streamkit/plugin/types"
	"go.bytecodealliance.org/cm"
	"strconv"
)

func lift_OptionString(f0 uint32, f1 *uint8, f2 uint32) (v cm.Option[string]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[string])(cm.Some[string](cm.LiftString[string]((*uint8)(f1), (uint32)(f2))))
}

func lift_AudioFrame(f0 uint32, f1 uint32, f2 *float32, f3 uint32) (v types.AudioFrame) {
	v.SampleRate = (uint32)(f0)
	v.Channels = (uint16)(f1)
	v.Samples = cm.LiftList[cm.List[float32]](f2, f3)
	return
}

func lift_Packet(f0 uint32, f1 uint32, f2 uint32, f3 *float32, f4 uint32) (v types.Packet) {
	switch f0 {
	case 0:
		return cm.New[types.Packet](0, lift_AudioFrame((uint32)(f1), (uint32)(f2), (*float32)(f3), (uint32)(f4)))
	case 1:
		return cm.New[types.Packet](1, cm.LiftString[string](cm.U32ToPointer[uint8](f1), (uint32)(f2)))
	case 2:
		return cm.New[types.Packet](2, cm.LiftList[cm.List[uint8]](cm.U32ToPointer[uint8](f1), (uint32)(f2)))
	}
	panic("lift variant: unknown case: " + strconv.Itoa(int(f0)))
}
