// Code generated by wit-bindgen-go. DO NOT EDIT.

package node

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "streamkit:plugin@0.1.0".

//go:wasmimport [export]streamkit:plugin/node@0.1.0 [resource-new]node-instance
//go:noescape
func wasmimport_NodeInstanceResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]streamkit:plugin/node@0.1.0 [resource-rep]node-instance
//go:noescape
func wasmimport_NodeInstanceResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]streamkit:plugin/node@0.1.0 [resource-drop]node-instance
//go:noescape
func wasmimport_NodeInstanceResourceDrop(self0 uint32)

//go:wasmexport streamkit:plugin/node@0.1.0#[dtor]node-instance
//export streamkit:plugin/node@0.1.0#[dtor]node-instance
func wasmexport_NodeInstanceDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.NodeInstance.Destructor(self)
	return
}

//go:wasmexport streamkit:plugin/node@0.1.0#[constructor]node-instance
//export streamkit:plugin/node@0.1.0#[constructor]node-instance
func wasmexport_Constructor(params0 uint32, params1 *uint8, params2 uint32) (result0 uint32) {
	params := lift_OptionString((uint32)(params0), (*uint8)(params1), (uint32)(params2))
	result := Exports.NodeInstance.Constructor(params)
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport streamkit:plugin/node@0.1.0#[method]node-instance.cleanup
//export streamkit:plugin/node@0.1.0#[method]node-instance.cleanup
func wasmexport_NodeInstanceCleanup(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.NodeInstance.Cleanup(self)
	return
}

//go:wasmexport streamkit:plugin/node@0.1.0#[method]node-instance.process
//export streamkit:plugin/node@0.1.0#[method]node-instance.process
func wasmexport_NodeInstanceProcess(self0 uint32, inputPin0 *uint8, inputPin1 uint32, packet0 uint32, packet1 uint32, packet2 uint32, packet3 *float32, packet4 uint32) (result *cm.Result[string, struct{}, string]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	inputPin := cm.LiftString[string]((*uint8)(inputPin0), (uint32)(inputPin1))
	packet := lift_Packet((uint32)(packet0), (uint32)(packet1), (uint32)(packet2), (*float32)(packet3), (uint32)(packet4))
	result_ := Exports.NodeInstance.Process(self, inputPin, packet)
	result = &result_
	return
}

//go:wasmexport streamkit:plugin/node@0.1.0#[method]node-instance.update-params
//export streamkit:plugin/node@0.1.0#[method]node-instance.update-params
func wasmexport_NodeInstanceUpdateParams(self0 uint32, params0 uint32, params1 *uint8, params2 uint32) (result *cm.Result[string, struct{}, string]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	params := lift_OptionString((uint32)(params0), (*uint8)(params1), (uint32)(params2))
	result_ := Exports.NodeInstance.UpdateParams(self, params)
	result = &result_
	return
}

//go:wasmexport streamkit:plugin/node@0.1.0#metadata
//export streamkit:plugin/node@0.1.0#metadata
func wasmexport_Metadata() (result *NodeMetadata) {
	result_ := Exports.Metadata()
	result = &result_
	return
}
