// Code generated by wit-bindgen-go. DO NOT EDIT.

package node

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "streamkit:plugin/node@0.1.0".
var Exports struct {
	// NodeInstance represents the caller-defined exports for resource "streamkit:plugin/node@0.1.0#node-instance".
	NodeInstance struct {
		// Destructor represents the caller-defined, exported destructor for resource "node-instance".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Constructor represents the caller-defined, exported constructor for resource "node-instance".
		//
		// Construct a new stateful node instance with optional parameters (JSON string)
		//
		//	constructor(params: option<string>)
		Constructor func(params cm.Option[string]) (result NodeInstance)

		// Cleanup represents the caller-defined, exported method "cleanup".
		//
		// Clean up any resources associated with this instance
		//
		//	cleanup: func()
		Cleanup func(self cm.Rep)

		// Process represents the caller-defined, exported method "process".
		//
		// Process an incoming packet from a specific input pin using this instance's state
		//
		//	process: func(input-pin: string, packet: packet) -> result<_, string>
		Process func(self cm.Rep, inputPin string, packet Packet) (result cm.Result[string, struct{}, string])

		// UpdateParams represents the caller-defined, exported method "update-params".
		//
		// Update the runtime parameters for this instance. The payload is a JSON string.
		//
		//	update-params: func(params: option<string>) -> result<_, string>
		UpdateParams func(self cm.Rep, params cm.Option[string]) (result cm.Result[string, struct{}, string])
	}

	// Metadata represents the caller-defined, exported function "metadata".
	//
	// Get metadata about this node type
	//
	//	metadata: func() -> node-metadata
	Metadata func() (result NodeMetadata)
}
