// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package node represents the exported interface "streamkit:plugin/node@0.1.0".
//
// The main interface that plugins must implement
package node

import (
	"github.com/streamkit/streamkit-codex/plugin-sdk/go/bindings/streamkit/plugin/types"
	"go.bytecodealliance.org/cm"
)

// NodeMetadata represents the type alias "streamkit:plugin/node@0.1.0#node-metadata".
//
// See [types.NodeMetadata] for more information.
type NodeMetadata = types.NodeMetadata

// Packet represents the type alias "streamkit:plugin/node@0.1.0#packet".
//
// See [types.Packet] for more information.
type Packet = types.Packet

// NodeInstance represents the exported resource "streamkit:plugin/node@0.1.0#node-instance".
//
// A stateful node instance resource.
//
//	resource node-instance
type NodeInstance cm.Resource

// NodeInstanceResourceNew represents the imported resource-new for resource "node-instance".
//
// Creates a new resource handle.
//
//go:nosplit
func NodeInstanceResourceNew(rep cm.Rep) (result NodeInstance) {
	rep0 := cm.Reinterpret[uint32](rep)
	result0 := wasmimport_NodeInstanceResourceNew((uint32)(rep0))
	result = cm.Reinterpret[NodeInstance]((uint32)(result0))
	return
}

// ResourceRep represents the imported resource-rep for resource "node-instance".
//
// Returns the underlying resource representation.
//
//go:nosplit
func (self NodeInstance) ResourceRep() (result cm.Rep) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_NodeInstanceResourceRep((uint32)(self0))
	result = cm.Reinterpret[cm.Rep]((uint32)(result0))
	return
}

// ResourceDrop represents the imported resource-drop for resource "node-instance".
//
// Drops a resource handle.
//
//go:nosplit
func (self NodeInstance) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_NodeInstanceResourceDrop((uint32)(self0))
	return
}

func init() {
	Exports.NodeInstance.Destructor = func(self cm.Rep) {}
}
