// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

import (
	"github.com/streamkit/streamkit-codex/plugin-sdk/go/bindings/streamkit/plugin/types"
	"go.bytecodealliance.org/cm"
)

func lower_AudioFrame(v types.AudioFrame) (f0 uint32, f1 uint32, f2 *float32, f3 uint32) {
	f0 = (uint32)(v.SampleRate)
	f1 = (uint32)(v.Channels)
	f2, f3 = cm.LowerList(v.Samples)
	return
}

func lower_Packet(v types.Packet) (f0 uint32, f1 uint32, f2 uint32, f3 *float32, f4 uint32) {
	f0 = (uint32)(v.Tag())
	switch f0 {
	case 0: // audio
		v1, v2, v3, v4 := lower_AudioFrame(*cm.Case[types.AudioFrame](&v, 0))
		f1 = (uint32)(v1)
		f2 = (uint32)(v2)
		f3 = (*float32)(v3)
		f4 = (uint32)(v4)
	case 1: // text
		v1, v2 := cm.LowerString(*cm.Case[string](&v, 1))
		f1 = (uint32)(cm.PointerToU32(v1))
		f2 = (uint32)(v2)
	case 2: // binary
		v1, v2 := cm.LowerList(*cm.Case[cm.List[uint8]](&v, 2))
		f1 = (uint32)(cm.PointerToU32(v1))
		f2 = (uint32)(v2)
	}
	return
}
