// Code generated by wit-bindgen-go. DO NOT EDIT.

package host

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "streamkit:plugin@0.1.0".

//go:wasmimport streamkit:plugin/host@0.1.0 send-output
//go:noescape
func wasmimport_SendOutput(pinName0 *uint8, pinName1 uint32, packet0 uint32, packet1 uint32, packet2 uint32, packet3 *float32, packet4 uint32, result *cm.Result[string, struct{}, string])

//go:wasmimport streamkit:plugin/host@0.1.0 log
//go:noescape
func wasmimport_Log(level0 uint32, message0 *uint8, message1 uint32)
