// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package host represents the imported interface "streamkit:plugin/host@0.1.0".
//
// Host functions that plugins can call
package host

import (
	"github.com/streamkit/streamkit-codex/plugin-sdk/go/bindings/streamkit/plugin/types"
	"go.bytecodealliance.org/cm"
)

// Packet represents the type alias "streamkit:plugin/host@0.1.0#packet".
//
// See [types.Packet] for more information.
type Packet = types.Packet

// LogLevel represents the enum "streamkit:plugin/host@0.1.0#log-level".
//
// Log levels for host logging
//
//	enum log-level {
//		debug,
//		info,
//		warn,
//		error
//	}
type LogLevel uint8

const (
	LogLevelDebug LogLevel = iota
	LogLevelInfo
	LogLevelWarn
	LogLevelError
)

var _LogLevelStrings = [4]string{
	"debug",
	"info",
	"warn",
	"error",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e LogLevel) String() string {
	return _LogLevelStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e LogLevel) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *LogLevel) UnmarshalText(text []byte) error {
	return _LogLevelUnmarshalCase(e, text)
}

var _LogLevelUnmarshalCase = cm.CaseUnmarshaler[LogLevel](_LogLevelStrings[:])

// SendOutput represents the imported function "send-output".
//
// Send a packet to an output pin
//
//	send-output: func(pin-name: string, packet: packet) -> result<_, string>
//
//go:nosplit
func SendOutput(pinName string, packet Packet) (result cm.Result[string, struct{}, string]) {
	pinName0, pinName1 := cm.LowerString(pinName)
	packet0, packet1, packet2, packet3, packet4 := lower_Packet(packet)
	wasmimport_SendOutput((*uint8)(pinName0), (uint32)(pinName1), (uint32)(packet0), (uint32)(packet1), (uint32)(packet2), (*float32)(packet3), (uint32)(packet4), &result)
	return
}

// Log represents the imported function "log".
//
// Log a message to the host
//
//	log: func(level: log-level, message: string)
//
//go:nosplit
func Log(level LogLevel, message string) {
	level0 := (uint32)(level)
	message0, message1 := cm.LowerString(message)
	wasmimport_Log((uint32)(level0), (*uint8)(message0), (uint32)(message1))
	return
}
