// SPDX-FileCopyrightText: © 2025 StreamKit Contributors
//
// SPDX-License-Identifier: MPL-2.0

//! Integration tests for the embedded MCP (Model Context Protocol) server.
//!
//! These tests exercise the MCP endpoint through real HTTP requests,
//! verifying auth enforcement, tool routing, and permission filtering.
//!
//! Requires the `mcp` feature: `cargo test --features mcp -p streamkit-server`

#![cfg(feature = "mcp")]
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::disallowed_macros,
    clippy::uninlined_format_args
)]

use axum::http::StatusCode;
use reqwest::header::{ACCEPT, AUTHORIZATION, CONTENT_TYPE};
use serde_json::json;
use std::net::SocketAddr;
use std::sync::Arc;
use streamkit_server::Config;
use tempfile::TempDir;
use tokio::net::TcpListener;
use tokio::time::Duration;

/// Poll `/healthz` until the server is ready (up to 2 s).
async fn wait_for_healthz(addr: SocketAddr) {
    let client = reqwest::Client::new();
    let url = format!("http://{addr}/healthz");
    for _ in 0..40 {
        if client.get(&url).send().await.is_ok() {
            return;
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    panic!("Server at {addr} did not become healthy within 2 s");
}

/// Start a test server with MCP enabled and built-in auth.
///
/// # Panics
///
/// Panics if the TCP listener cannot be bound (including `PermissionDenied`).
async fn start_mcp_server() -> (SocketAddr, tokio::task::JoinHandle<()>, String, TempDir) {
    let listener =
        TcpListener::bind("127.0.0.1:0").await.expect("Failed to bind test server listener");
    let addr = listener.local_addr().unwrap();
    let temp_dir = TempDir::new().unwrap();

    let mut config = Config::default();
    config.mcp.enabled = true;
    config.auth.mode = streamkit_server::config::AuthMode::Enabled;
    config.auth.state_dir = temp_dir.path().to_string_lossy().to_string();

    let auth_state = streamkit_server::auth::AuthState::new(&config.auth, true)
        .await
        .expect("Failed to init auth state");
    let auth_state = Arc::new(auth_state);

    let admin_token_path = temp_dir.path().join("admin.token");
    let admin_token =
        tokio::fs::read_to_string(&admin_token_path).await.expect("Missing admin.token");
    let admin_token = admin_token.trim().to_string();

    let (app, _state) = streamkit_server::server::create_app(config, Some(auth_state));
    let server_handle = tokio::spawn(async move {
        axum::serve(listener, app.into_make_service()).await.unwrap();
    });

    wait_for_healthz(addr).await;
    (addr, server_handle, admin_token, temp_dir)
}

/// Start a test server with restricted permissions (no create_sessions).
async fn start_restricted_mcp_server() -> (SocketAddr, tokio::task::JoinHandle<()>, String, TempDir)
{
    let listener =
        TcpListener::bind("127.0.0.1:0").await.expect("Failed to bind test server listener");
    let addr = listener.local_addr().unwrap();
    let temp_dir = TempDir::new().unwrap();

    let mut config = Config::default();
    config.mcp.enabled = true;
    config.auth.mode = streamkit_server::config::AuthMode::Enabled;
    config.auth.state_dir = temp_dir.path().to_string_lossy().to_string();

    // Restrict the admin role: disable create_sessions.
    // The admin token generated by AuthState::new has role="admin".
    if let Some(admin_perms) = config.permissions.roles.get_mut("admin") {
        admin_perms.create_sessions = false;
    }

    let auth_state = streamkit_server::auth::AuthState::new(&config.auth, true)
        .await
        .expect("Failed to init auth state");
    let auth_state = Arc::new(auth_state);

    let admin_token_path = temp_dir.path().join("admin.token");
    let admin_token =
        tokio::fs::read_to_string(&admin_token_path).await.expect("Missing admin.token");
    let admin_token = admin_token.trim().to_string();

    let (app, _state) = streamkit_server::server::create_app(config, Some(auth_state));
    let server_handle = tokio::spawn(async move {
        axum::serve(listener, app.into_make_service()).await.unwrap();
    });

    wait_for_healthz(addr).await;
    (addr, server_handle, admin_token, temp_dir)
}

/// Send a JSON-RPC request to the MCP endpoint.
async fn mcp_post(
    client: &reqwest::Client,
    addr: SocketAddr,
    body: &serde_json::Value,
    auth_header: Option<&str>,
) -> reqwest::Response {
    let mut req = client
        .post(format!("http://{addr}/api/v1/mcp"))
        .header(CONTENT_TYPE, "application/json")
        .header(ACCEPT, "application/json, text/event-stream")
        .json(body);

    if let Some(token) = auth_header {
        req = req.header(AUTHORIZATION, format!("Bearer {token}"));
    }

    req.send().await.expect("Failed to send MCP request")
}

/// Send a JSON-RPC request with a session ID.
async fn mcp_post_with_session(
    client: &reqwest::Client,
    addr: SocketAddr,
    body: &serde_json::Value,
    token: &str,
    session_id: &str,
) -> reqwest::Response {
    client
        .post(format!("http://{addr}/api/v1/mcp"))
        .header(CONTENT_TYPE, "application/json")
        .header(ACCEPT, "application/json, text/event-stream")
        .header(AUTHORIZATION, format!("Bearer {token}"))
        .header("mcp-session-id", session_id)
        .json(body)
        .send()
        .await
        .expect("Failed to send MCP request")
}

/// Initialize an MCP session and return the session ID.
async fn init_mcp_session(client: &reqwest::Client, addr: SocketAddr, token: &str) -> String {
    let init = json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "initialize",
        "params": {
            "protocolVersion": "2025-03-26",
            "capabilities": {},
            "clientInfo": { "name": "test", "version": "0.1" }
        }
    });
    let res = mcp_post(client, addr, &init, Some(token)).await;
    assert_eq!(res.status(), StatusCode::OK);

    let session_id = res
        .headers()
        .get("mcp-session-id")
        .expect("missing mcp-session-id header")
        .to_str()
        .unwrap()
        .to_string();

    // Send initialized notification
    let initialized = json!({
        "jsonrpc": "2.0",
        "method": "notifications/initialized"
    });
    let _ = mcp_post_with_session(client, addr, &initialized, token, &session_id).await;

    session_id
}

/// Extract JSON-RPC result from SSE response body.
fn extract_sse_json(body_text: &str) -> serde_json::Value {
    let json_str = body_text
        .lines()
        .filter_map(|l| l.strip_prefix("data:"))
        .map(str::trim)
        .find(|s| s.starts_with('{'))
        .expect("no SSE data line with JSON found in response");
    serde_json::from_str(json_str).expect("invalid JSON in SSE data")
}

// -----------------------------------------------------------------------
// Tests
// -----------------------------------------------------------------------

#[tokio::test]
async fn mcp_unauthenticated_request_is_rejected() {
    let _ = tracing_subscriber::fmt::try_init();

    let (addr, _handle, _token, _dir) = start_mcp_server().await;
    let client = reqwest::Client::new();

    // JSON-RPC initialize request without auth
    let body = json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "initialize",
        "params": {
            "protocolVersion": "2025-03-26",
            "capabilities": {},
            "clientInfo": { "name": "test", "version": "0.1" }
        }
    });

    let res = mcp_post(&client, addr, &body, None).await;
    assert_eq!(res.status(), StatusCode::UNAUTHORIZED);
}

#[tokio::test]
async fn mcp_authenticated_initialize_succeeds() {
    let _ = tracing_subscriber::fmt::try_init();

    let (addr, _handle, token, _dir) = start_mcp_server().await;
    let client = reqwest::Client::new();

    let body = json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "initialize",
        "params": {
            "protocolVersion": "2025-03-26",
            "capabilities": {},
            "clientInfo": { "name": "test", "version": "0.1" }
        }
    });

    let res = mcp_post(&client, addr, &body, Some(&token)).await;
    assert_eq!(res.status(), StatusCode::OK);
}

#[tokio::test]
async fn mcp_validate_pipeline_returns_diagnostics() {
    let _ = tracing_subscriber::fmt::try_init();

    let (addr, _handle, token, _dir) = start_mcp_server().await;
    let client = reqwest::Client::new();

    let session_id = init_mcp_session(&client, addr, &token).await;

    // Call validate_pipeline with invalid YAML
    let validate = json!({
        "jsonrpc": "2.0",
        "id": 2,
        "method": "tools/call",
        "params": {
            "name": "validate_pipeline",
            "arguments": {
                "yaml": "not: valid: yaml: [["
            }
        }
    });
    let res = mcp_post_with_session(&client, addr, &validate, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    // Response is SSE stream — extract JSON-RPC result from `data:` lines.
    let body_text = res.text().await.expect("failed to read response body");
    let body = extract_sse_json(&body_text);
    let result = &body["result"];
    assert!(!result.is_null(), "expected result in response, got: {body}");

    // The tool should return text content with validation diagnostics
    let content = &result["content"][0]["text"];
    assert!(content.is_string(), "expected text content in result");
    let text = content.as_str().unwrap();
    let parsed: serde_json::Value = serde_json::from_str(text).expect("tool output not valid JSON");
    assert_eq!(parsed["valid"], false);
    assert!(!parsed["errors"].as_array().unwrap().is_empty());
}

#[tokio::test]
async fn mcp_create_session_permission_denied() {
    let _ = tracing_subscriber::fmt::try_init();

    let (addr, _handle, token, _dir) = start_restricted_mcp_server().await;
    let client = reqwest::Client::new();

    let session_id = init_mcp_session(&client, addr, &token).await;

    // Try to create a session — should be denied by permissions
    let create = json!({
        "jsonrpc": "2.0",
        "id": 2,
        "method": "tools/call",
        "params": {
            "name": "create_session",
            "arguments": {
                "yaml": "nodes:\n  tone:\n    kind: streamkit::tone_generator\n    params:\n      frequency: 440\n      sample_rate: 48000\n      duration: 1.0",
                "name": "test-denied"
            }
        }
    });
    let res = mcp_post_with_session(&client, addr, &create, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    let body_text = res.text().await.expect("failed to read response body");
    let body = extract_sse_json(&body_text);
    let error = &body["error"];
    assert!(!error.is_null(), "expected error in response, got: {body}");
    let error_msg = error["message"].as_str().unwrap_or("");
    assert!(
        error_msg.contains("Permission denied") || error_msg.contains("permission"),
        "expected permission error, got: {error_msg}"
    );
}

#[tokio::test]
async fn mcp_destroy_session_nonexistent_returns_error() {
    let _ = tracing_subscriber::fmt::try_init();

    let (addr, _handle, token, _dir) = start_mcp_server().await;
    let client = reqwest::Client::new();

    let session_id = init_mcp_session(&client, addr, &token).await;

    // Try to destroy a session that doesn't exist
    let destroy = json!({
        "jsonrpc": "2.0",
        "id": 2,
        "method": "tools/call",
        "params": {
            "name": "destroy_session",
            "arguments": {
                "session_id": "nonexistent-session-id-12345"
            }
        }
    });
    let res = mcp_post_with_session(&client, addr, &destroy, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    let body_text = res.text().await.expect("failed to read response body");
    let body = extract_sse_json(&body_text);
    let error = &body["error"];
    assert!(!error.is_null(), "expected error for nonexistent session destroy, got: {body}");
}

#[tokio::test]
async fn mcp_config_endpoint_validation() {
    // Verify that McpConfig::validate rejects bad endpoints at config-load time
    let mut mcp_config = streamkit_server::config::McpConfig::default();

    // Disabled config should always pass
    mcp_config.enabled = false;
    mcp_config.endpoint = "/bad/path".to_string();
    assert!(mcp_config.validate().is_ok());

    // Enabled with bad prefix should fail
    mcp_config.enabled = true;
    mcp_config.endpoint = "/bad/path".to_string();
    assert!(mcp_config.validate().is_err());

    // Auth bypass path should fail
    mcp_config.endpoint = "/api/v1/auth/mcp".to_string();
    assert!(mcp_config.validate().is_err());

    // Path traversal should fail
    mcp_config.endpoint = "/api/v1/../mcp".to_string();
    assert!(mcp_config.validate().is_err());

    // Only /api/ prefix should fail (missing version/mcp segments)
    mcp_config.endpoint = "/api/".to_string();
    assert!(mcp_config.validate().is_err());

    // Non-versioned path should fail
    mcp_config.endpoint = "/api/mcp".to_string();
    assert!(mcp_config.validate().is_err());

    // Colliding with existing routes should fail (wrong third segment)
    mcp_config.endpoint = "/api/v1/sessions".to_string();
    assert!(mcp_config.validate().is_err());

    // Valid default endpoint should pass
    mcp_config.endpoint = "/api/v1/mcp".to_string();
    assert!(mcp_config.validate().is_ok());

    // Valid with subpath should pass
    mcp_config.endpoint = "/api/v2/mcp/extra".to_string();
    assert!(mcp_config.validate().is_ok());
}

// -----------------------------------------------------------------------
// Positive-path tests
// -----------------------------------------------------------------------

/// Minimal valid pipeline YAML for dynamic sessions.
const PASSTHROUGH_YAML: &str = "nodes:\n  pass:\n    kind: core::passthrough";

#[tokio::test]
async fn mcp_list_nodes_returns_definitions() {
    let _ = tracing_subscriber::fmt::try_init();

    let (addr, _handle, token, _dir) = start_mcp_server().await;
    let client = reqwest::Client::new();
    let session_id = init_mcp_session(&client, addr, &token).await;

    let list = json!({
        "jsonrpc": "2.0",
        "id": 2,
        "method": "tools/call",
        "params": {
            "name": "list_nodes",
            "arguments": {}
        }
    });
    let res = mcp_post_with_session(&client, addr, &list, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    let body_text = res.text().await.unwrap();
    let body = extract_sse_json(&body_text);
    let result = &body["result"];
    assert!(!result.is_null(), "expected result, got: {body}");

    let text = result["content"][0]["text"].as_str().expect("expected text content");
    let defs: Vec<serde_json::Value> = serde_json::from_str(text).expect("expected JSON array");
    assert!(!defs.is_empty(), "list_nodes should return at least one definition");

    // Verify passthrough and synthetic nodes are present
    let kinds: Vec<&str> = defs.iter().filter_map(|d| d["kind"].as_str()).collect();
    assert!(kinds.contains(&"core::passthrough"), "missing core::passthrough in: {kinds:?}");
    assert!(kinds.contains(&"streamkit::http_input"), "missing synthetic http_input in: {kinds:?}");
}

#[tokio::test]
async fn mcp_create_list_get_destroy_session_round_trip() {
    let _ = tracing_subscriber::fmt::try_init();

    let (addr, _handle, token, _dir) = start_mcp_server().await;
    let client = reqwest::Client::new();
    let session_id = init_mcp_session(&client, addr, &token).await;

    // 1. Create a session
    let create = json!({
        "jsonrpc": "2.0",
        "id": 2,
        "method": "tools/call",
        "params": {
            "name": "create_session",
            "arguments": {
                "yaml": PASSTHROUGH_YAML,
                "name": "mcp-roundtrip-test"
            }
        }
    });
    let res = mcp_post_with_session(&client, addr, &create, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    let body_text = res.text().await.unwrap();
    let body = extract_sse_json(&body_text);
    let result = &body["result"];
    assert!(!result.is_null(), "expected result from create_session, got: {body}");

    let text = result["content"][0]["text"].as_str().expect("expected text content");
    let created: serde_json::Value = serde_json::from_str(text).expect("expected JSON");
    let skit_session_id = created["session_id"].as_str().expect("missing session_id");
    assert_eq!(created["name"].as_str(), Some("mcp-roundtrip-test"));
    assert!(created["created_at"].as_str().is_some());

    // 2. List sessions — our session should appear
    let list = json!({
        "jsonrpc": "2.0",
        "id": 3,
        "method": "tools/call",
        "params": {
            "name": "list_sessions",
            "arguments": {}
        }
    });
    let res = mcp_post_with_session(&client, addr, &list, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    let body_text = res.text().await.unwrap();
    let body = extract_sse_json(&body_text);
    let text = body["result"]["content"][0]["text"].as_str().expect("expected text");
    let sessions: Vec<serde_json::Value> = serde_json::from_str(text).expect("expected JSON array");
    assert!(
        sessions.iter().any(|s| s["id"].as_str() == Some(skit_session_id)),
        "created session not found in list_sessions"
    );

    // 3. Get pipeline — should return the passthrough node
    let get = json!({
        "jsonrpc": "2.0",
        "id": 4,
        "method": "tools/call",
        "params": {
            "name": "get_pipeline",
            "arguments": {
                "session_id": skit_session_id
            }
        }
    });
    let res = mcp_post_with_session(&client, addr, &get, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    let body_text = res.text().await.unwrap();
    let body = extract_sse_json(&body_text);
    let text = body["result"]["content"][0]["text"].as_str().expect("expected text");
    let pipeline: serde_json::Value = serde_json::from_str(text).expect("expected JSON");
    assert!(pipeline["nodes"]["pass"].is_object(), "expected 'pass' node in pipeline");

    // 4. Destroy the session
    let destroy = json!({
        "jsonrpc": "2.0",
        "id": 5,
        "method": "tools/call",
        "params": {
            "name": "destroy_session",
            "arguments": {
                "session_id": skit_session_id
            }
        }
    });
    let res = mcp_post_with_session(&client, addr, &destroy, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    let body_text = res.text().await.unwrap();
    let body = extract_sse_json(&body_text);
    let result = &body["result"];
    assert!(!result.is_null(), "expected result from destroy_session, got: {body}");
    let text = result["content"][0]["text"].as_str().expect("expected text");
    let destroyed: serde_json::Value = serde_json::from_str(text).expect("expected JSON");
    assert_eq!(destroyed["session_id"].as_str(), Some(skit_session_id));

    // 5. Verify session is gone
    let res = mcp_post_with_session(&client, addr, &list, &token, &session_id).await;
    assert_eq!(res.status(), StatusCode::OK);

    let body_text = res.text().await.unwrap();
    let body = extract_sse_json(&body_text);
    let text = body["result"]["content"][0]["text"].as_str().expect("expected text");
    let sessions: Vec<serde_json::Value> = serde_json::from_str(text).expect("expected JSON array");
    assert!(
        !sessions.iter().any(|s| s["id"].as_str() == Some(skit_session_id)),
        "destroyed session should not appear in list_sessions"
    );
}
